version: 2.1

jobs:
  build-prod:
    docker:
      - image: cimg/node:18.20.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ~/.npm
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Building the application
          command: npm run build:prod
      - run:
          name: Install Firefox
          command: |
            sudo apt-get update
            sudo apt-get install -y firefox
      - run:
          name: Run test cases
          command: npm test --passWithNoTests
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
            - node_modules/
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install -y unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Deploy to S3
          command: |
            DIST_OUTPUT_DIR=$(find dist -maxdepth 1 -type d | awk 'NR==2')
            aws s3 sync ${DIST_OUTPUT_DIR}/ s3://$S3_BUCKET_NAME --delete

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build-prod:
          filters:
            branches:
              only:
                - main
                - master
